language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash deploy.sh
