version: '3.9'
services: 
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    ports: 
      - 5000:5000
    volumes: 
      - .:/app
